### ISSUE TITLE
Requirements not covering all dependencies for proper working

### ISSUE THREAD

**Issue by mkilijanek** [CERT-Polska/mwdblib#1]
I encountered that requirements.txt is not covering all dependencies for mwdblib to work. 
Missing dependencies:
- click
- keyring
- beautifultable
- humanize
- click_default_group

Error encountered in attached file [hardtimes.txt](https://github.com/CERT-Polska/mwdblib/files/3975388/hardtimes.txt)

**Comment by psrok1** [comment]
If you want to use CLI, you need to explicitly request `[cli]` extras during installation:
```
$ pip install malduck[cli]
```
We should probably provide some warning message in case of missing dependencies. It seems that wheel doesn't fully support the extras syntax in `console_script` section (mentioned  [here in packaging.python.org](https://packaging.python.org/specifications/entry-points/), used [here in mwdblib code](https://github.com/CERT-Polska/mwdblib/blob/87904bf1ae067defee45b18fb57609460224e0c7/setup.py#L35) ) and installs script even if no extras are requested. 

Maybe I'm missing something, but currently I don't see clean solution different than wrapping [src/cli/\_\_init\_\_.py](https://github.com/CERT-Polska/mwdblib/blob/87904bf1ae067defee45b18fb57609460224e0c7/src/cli/__init__.py) with `ImportError` handling and showing the message. I'm open to any suggestions.

**Comment by psrok1** [comment]
Fixed: 3.2.0 is showing appropriate message on ImportError https://github.com/CERT-Polska/mwdblib/commit/0afe51459b5a4a46bf06eb516b67365069eae585
