### ISSUE TITLE
Allow user to specify search query in "listen_for_objects"

### ISSUE THREAD

**Issue by nazywam** [CERT-Polska/mwdblib#2]
Being able to query specific objects could be pretty useful.
Current workaround is probably to get all available objects and then do the filtering which is a lot less convenient and efficient.

Usage example:
```python
for config in mwdb.listen_for_configs(query="family:danabot"):
     print(config.cfg)
```

**Comment by psrok1** [comment]
It would be nice to check if pivot object exists in query results. Maybe we should add "AND dhash:<pivot dhash>" to query and check if we got any results?
