### ISSUE TITLE
Delete sample functionality

### ISSUE THREAD

**Issue by raw-data** [CERT-Polska/mwdblib#38]
Removing stored samples from mwdb Web UI is already possible in few clicks, yet the functionality is not available though any API endpoint. It would be a valuable addition, considering the automation / scripting functionality offered by mwdblib. 

On the one hand, it could be integrated as an additional method within `mwdblib.file.MWDBFile`, for single delete operation, or in addition, introduce a "bulk" delete function consuming results from, e.g MWDB.recent_files(), etc.

**Comment by psrok1** [comment]
Yes, it definitely should be implemented as `delete` method on MWDBObject level (that operation is pretty generic).

Bulk operation method is also interesting idea.

Currently you can access unsupported methods via direct APIClient calls e.g.
```
mwdb = MWDB()
...
mwdb.api.delete('object/{sha256}')
```
