### ISSUE TITLE
get_terminal_size

### ISSUE THREAD

**Issue by xorhex** [CERT-Polska/mwdblib#70]
Getting this error when running a query using the mwdb cli tool:

```
  File "/home/name/venv_mwdb/lib/python3.9/site-packages/mwdblib/cli/formatters/tabular.py", line 34, in format_table
    term_width, term_height = click.get_terminal_size()
AttributeError: module 'click' has no attribute 'get_terminal_size'
```

Should this be `os.get_terminal_size()` instead of `click.get_terminal_size()`?  https://github.com/CERT-Polska/mwdblib/blob/master/mwdblib/cli/formatters/tabular.py#L20

**Comment by psrok1** [comment]
Agree, `get_terminal_size` looks to be dropped from click 8.0.0 (https://click.palletsprojects.com/en/8.1.x/changes/#version-8-0-0)
![image](https://user-images.githubusercontent.com/8720367/161105948-78dd5050-cecb-4e64-9ef7-20c8cd135384.png)

So `shutil.get_terminal_size` should be used instead (https://docs.python.org/3/library/shutil.html#shutil.get_terminal_size). Temporary workaround is to install click 7.1.2.
